//---------------------------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated by T4Model template for T4 (https://github.com/linq2db/linq2db).
//    Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//---------------------------------------------------------------------------------------------------

#pragma warning disable 1591

using System;
using System.Collections.Generic;
using System.Linq;

using LinqToDB;
using LinqToDB.Mapping;

namespace SimpleBankApp.Infrastructure.Persistance.Linq2DB
{
	/// <summary>
	/// Database       : SimpleBankDB
	/// Data Source    : localhost
	/// Server Version : 15.00.2110
	/// </summary>
	public partial class SimpleBankDb : LinqToDB.Data.DataConnection
	{
		public ITable<BankAccount> BankAccounts { get { return this.GetTable<BankAccount>(); } }
		public ITable<User>        Users        { get { return this.GetTable<User>(); } }

		public SimpleBankDb()
		{
			InitDataContext();
			InitMappingSchema();
		}

		public SimpleBankDb(string configuration)
			: base(configuration)
		{
			InitDataContext();
			InitMappingSchema();
		}

		partial void InitDataContext  ();
		partial void InitMappingSchema();
	}

	[Table(Schema="dbo", Name="BankAccount")]
	public partial class BankAccount
	{
		[PrimaryKey, NotNull] public Guid     Id            { get; set; } // uniqueidentifier
		[Column,     NotNull] public Guid     UserId        { get; set; } // uniqueidentifier
		[Column,     NotNull] public decimal  Balance       { get; set; } // decimal(18, 2)
		[Column,     NotNull] public DateTime CreatedOn     { get; set; } // datetime
		[Column,     NotNull] public DateTime LastUpdatedOn { get; set; } // datetime
	}

	[Table(Schema="dbo", Name="User")]
	public partial class User
	{
		[PrimaryKey, NotNull] public Guid     Id            { get; set; } // uniqueidentifier
		[Column,     NotNull] public string   FirstName     { get; set; } // nvarchar(50)
		[Column,     NotNull] public string   LastName      { get; set; } // nvarchar(50)
		[Column,     NotNull] public string   Email         { get; set; } // nvarchar(100)
		[Column,     NotNull] public string   Password      { get; set; } // nvarchar(255)
		[Column,     NotNull] public DateTime CreatedOn     { get; set; } // datetime
		[Column,     NotNull] public DateTime LastUpdatedOn { get; set; } // datetime
	}

	public static partial class TableExtensions
	{
		public static BankAccount Find(this ITable<BankAccount> table, Guid Id)
		{
			return table.FirstOrDefault(t =>
				t.Id == Id);
		}

		public static User Find(this ITable<User> table, Guid Id)
		{
			return table.FirstOrDefault(t =>
				t.Id == Id);
		}
	}
}

#pragma warning restore 1591
